default: &default
  url: redis://redis:6379

test:
  <<: *default

development:
  <<: *default

staging:
  <<: *default
  url: <%= ENV.fetch("REDIS_URL", "redis://redis:6379") %>

production:
  <<: *default
  url: <%= ENV.fetch("REDIS_URL", "redis://redis:6379") %>
